
DEFC PLUGIN_ORG=$8000

DEFC PLUGIN_OK=1
DEFC PLUGIN_RESTORE_SCREEN=2
DEFC PLUGIN_RESTORE_BUFFERS=4
DEFC PLUGIN_NAVIGATE=8
DEFC PLUGIN_STATUS_MESSAGE=16
DEFC PLUGIN_DATA_RETURNED=64
DEFC PLUGIN_ERROR=128

DEFC PLUGIN_NAVIGATE_NEXT=1
DEFC PLUGIN_NAVIGATE_PREVIOUS=2
DEFC PLUGIN_NAVIGATE_FIRST=3
DEFC PLUGIN_NAVIGATE_LAST=4

DEFC PLUGIN_FLAGS1_COPY_SETTINGS=1
DEFC PLUGIN_FLAGS1_MMC_ONLY=2

DEFC PLUGIN_SETTING_OFFSET_TOP_LINE=0
DEFC PLUGIN_SETTING_OFFSET_BOTTOM_LINE=1
DEFC PLUGIN_SETTING_OFFSET_BORDER=2
DEFC PLUGIN_SETTING_OFFSET_FILE=3
DEFC PLUGIN_SETTING_OFFSET_DIRECTORY=4
DEFC PLUGIN_SETTING_OFFSET_SELECTION=5
DEFC PLUGIN_SETTING_OFFSET_DEVICE=6
DEFC PLUGIN_SETTING_OFFSET_FLAGS=7
DEFC PLUGIN_SETTING_OFFSET_FLAGS2=8
DEFC PLUGIN_SETTING_OFFSET_KEY_UP=9
DEFC PLUGIN_SETTING_OFFSET_KEY_DOWN=10
DEFC PLUGIN_SETTING_OFFSET_KEY_LEFT=11
DEFC PLUGIN_SETTING_OFFSET_KEY_RIGHT=12
DEFC PLUGIN_SETTING_OFFSET_KEY_SELECT=13

DEFC PLUGIN_SETTING_MAX = 14

DEFC PLUGIN_STATUS_SCREEN_ADDR = $50e0 + 24	; x, 20, y = bottom line
